name: Publish YML

on:
  push:
    tags:
      - 'cli-*'

jobs:
  publish-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./cli"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Set version
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^cli-//')
          sed -i "s/version = \"0.0.0\"/version = \"$VERSION\"/" Cargo.toml
      - name: Cargo Login
        run: cargo login ${{secrets.CRATES_IO_PUBLISH}}
      - name: Publish crate
        run: cargo publish --allow-dirty
